### ISSUE TITLE
Error loading the icon using custom pack from fluttericon.com

### ISSUE THREAD

**Issue by SamiAlsubhi** [ilikerobots/fluttericon_pkg#10]
I have selected an icon to be used and then i downloaded the pack. I copied the font into the fonts folder and adjusted pubspec.yaml to load the font. The font is loaded correctly as per the debug logs.

```yaml
flutter:
    uses-material-design: true
    fonts:
        - family:  MyFlutterApp
          fonts:
            - asset: fonts/MyFlutterApp.ttf
```

Then I added the dart file to load the icon data:

```dart
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData handPointer =
      IconData(0xf25a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
```

Then I used it by importing the class and using the icon data in `Icon` class.
```dart
Icon(CustomIcons.handPointer))
```
However instead of showing the icon, I get a question mark bordered by a box!
what am I doing wrong?
